// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.
#include <iostream>
using namespace std;

int main(int argc, char** argv) {
	unsigned int fib1=1, fib2=2, fib3; // base case
	unsigned int ans=2; // in the base case, we have 2 which is even
	do {
		fib3 = fib1 + fib2;
		if(fib3%2 == 0) ans += fib3;
		fib1 = fib2;
		fib2 = fib3;
	} while(fib2<=4000000);
	cout << "Answer: " << ans << endl;
	return 0;
}